name       : qt6-webengine
version    : 6.2.2
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtwebengine-everywhere-src-6.2.2.tar.xz : 2d2dcde6e4678ea96e4203a6e585b73e23fb61f83b47330f1f00c25e481cd3b4
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : QtWebEngine integrates chromium's fast moving web capabilities into Qt6
description: |
    The Qt WebEngine module provides a web browser engine that makes it easy to embed content from the World Wide Web into your Qt application on platforms that do not have a native web engine.
clang      : yes
builddeps  :
    - pkgconfig(Qt6UiTools)
    - pkgconfig(Qt6WebChannel)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(jsoncpp)
    - pkgconfig(krb5)
    - pkgconfig(lcms2)
    - pkgconfig(libavformat)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsrtp2)
    - pkgconfig(libwebp)
    - pkgconfig(libxslt)
    - pkgconfig(minizip)
    - pkgconfig(nss)
    - pkgconfig(opus)
    - pkgconfig(python3)
    - pkgconfig(protobuf)
    - pkgconfig(re2)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - qt6-positioning-devel
    - designer6
    - gperf
    - nodejs-devel
    - snappy-devel
rundeps    :
    - devel :
        - gperf
        - nodejs-devel
        - re2-devel
        - snappy-devel
        - qt6-positioning-devel
        - qt6-tools-devel
        - qt6-webchannel-devel
environment: |
    export QMAKE_C=$CC
    export QMAKE_CXX=$CXX
    export QT_WEBENGINE_ICU_DAT_DIR=%workdir%/src/3rdparty/chromium/third_party/icu/common
setup      : |
    %patch -p1 < $pkgfiles/disable-spellchecker-demo.patch
    %cmake_ninja \
        -DCMAKE_TOOLCHAIN_FILE=/usr/lib64/cmake/Qt6/qt.toolchain.cmake \
        -DCMAKE_C_COMPILER=$CC \
        -DCMAKE_CXX_COMPILER=$CXX \
        -DQT_FEATURE_webengine_system_ffmpeg=ON \
        -DQT_FEATURE_webengine_system_icu=ON \
        -DQT_FEATURE_webengine_system_libevent=ON \
        -DQT_FEATURE_webengine_system_libxml=ON \
        -DQT_FEATURE_webengine_system_libxslt=ON \
        -DQT_FEATURE_webengine_system_re2=ON \
        -DQT_FEATURE_webengine_system_ninja=ON \
        -DQT_FEATURE_webengine_system_gn=OFF \
        -DQT_FEATURE_webengine_proprietary_codecs=ON \
        -DQT_FEATURE_webengine_kerberos=ON \
        -DQT_FEATURE_webengine_spellchecker=ON \
        -DQT_FEATURE_webengine_webrtc_pipewire=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $QT_WEBENGINE_ICU_DAT_DIR/*.dat -t $installdir/usr/share/qt6/resources
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
